spring.datasource.url: jdbc:mysql://localhost:3306/mytrainingbase?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: admin
spring.jpa.hibernate.ddl-auto: update
