spring.datasource.url: jdbc:mysql://localhost:3306/cc?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: admin
spring.jpa.hibernate.ddl-auto: update
#someParameter:
#  value: 5463